"""
Routing advisor — given (current_model, task_pattern) return ranked alternatives
with a ready-to-paste LiteLLM YAML snippet.

No I/O. Pure compute on the frozen pricing_table.
"""

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field

from milo_cost_auditor.pricing_table import (
    PRICING_TABLE,
    TASK_QUALITY_REQUIREMENT,
    ModelPrice,
    cheaper_than,
    lookup,
)


class RoutingAlternative(BaseModel):
    """One ranked alternative."""

    provider: str
    model: str
    input_per_million_usd: float
    output_per_million_usd: float
    avg_cost_delta_pct: float = Field(
        ..., description="Cost reduction vs current model, as a positive percentage"
    )
    quality_band: int
    quality_note: str
    why: str


class RoutingPlan(BaseModel):
    """Full plan: current model context, top-3 alternatives, LiteLLM YAML snippet."""

    current_model: str
    current_model_known: bool
    task_pattern: str
    min_quality_required: int
    alternatives: List[RoutingAlternative]
    litellm_yaml: str
    summary: str


_QUALITY_NOTES = {
    5: "frontier — same tier as current",
    4: "strong — small drop, fine for 80% of tasks",
    3: "capable — noticeable drop, fine for routine work",
    2: "small — only for tightly-scoped extraction/classify",
    1: "embedding/cheap — not a chat substitute",
}


def _quality_note(current: int, candidate: int) -> str:
    drop = current - candidate
    if drop <= 0:
        return "no quality drop"
    if drop == 1:
        return "1-band drop — usually unnoticeable on routine tasks"
    if drop == 2:
        return "2-band drop — only safe for extraction/classify"
    return "large quality drop — only for tightly scoped tasks"


def _avg(price: ModelPrice) -> float:
    return (price.input_per_million + price.output_per_million) / 2.0


def _litellm_snippet(current: str, alternatives: List[ModelPrice], task_pattern: str) -> str:
    """Generate a LiteLLM router config snippet."""
    primary = alternatives[0] if alternatives else None
    if primary is None:
        return (
            "# No cheaper alternative meets the quality bar for this task pattern.\n"
            f"# Keep using {current}.\n"
        )
    lines: List[str] = []
    lines.append("# Generated by Milo Cost Auditor — drop this into your LiteLLM proxy config.yaml")
    lines.append(f"# Replaces '{current}' for task pattern '{task_pattern}'.")
    lines.append("model_list:")
    for i, alt in enumerate(alternatives[:3]):
        priority = ["primary", "fallback-1", "fallback-2"][i]
        lines.append(f"  - model_name: {task_pattern}-router  # {priority}")
        lines.append(f"    litellm_params:")
        lines.append(f"      model: {alt.provider}/{alt.model}")
        lines.append(f"      # ~${_avg(alt):.2f}/1M tokens avg")
    lines.append("router_settings:")
    lines.append(f"  routing_strategy: simple-shuffle")
    lines.append(f"  fallbacks:")
    lines.append(f"    - {task_pattern}-router: [{current}]  # escalate to original on failure")
    return "\n".join(lines) + "\n"


def suggest_routing(current_model: str, task_pattern: str) -> RoutingPlan:
    """Suggest cheaper routing alternatives for (current_model, task_pattern)."""
    task_pattern = (task_pattern or "routine-synthesis").lower().strip()
    min_quality = TASK_QUALITY_REQUIREMENT.get(task_pattern, 3)

    current = lookup(current_model)
    known = current is not None

    if not known:
        # Unknown model — fall back to "what would I use for this task?"
        candidates = [m for m in PRICING_TABLE if m.quality_band >= min_quality]
        candidates.sort(key=_avg)
        top = candidates[:3]
        alternatives = [
            RoutingAlternative(
                provider=m.provider,
                model=m.model,
                input_per_million_usd=m.input_per_million,
                output_per_million_usd=m.output_per_million,
                avg_cost_delta_pct=0.0,
                quality_band=m.quality_band,
                quality_note=_QUALITY_NOTES[m.quality_band],
                why=f"I don't know '{current_model}', so I'm recommending the cheapest "
                f"model that still meets quality band {min_quality} for {task_pattern}.",
            )
            for m in top
        ]
        snippet = _litellm_snippet(current_model, top, task_pattern)
        return RoutingPlan(
            current_model=current_model,
            current_model_known=False,
            task_pattern=task_pattern,
            min_quality_required=min_quality,
            alternatives=alternatives,
            litellm_yaml=snippet,
            summary=(
                f"I don't have a price for '{current_model}' in my 2026-05 table. "
                f"Top 3 cheapest models meeting quality band {min_quality} listed."
            ),
        )

    peers = cheaper_than(current, min_quality=min_quality)
    if not peers:
        return RoutingPlan(
            current_model=current_model,
            current_model_known=True,
            task_pattern=task_pattern,
            min_quality_required=min_quality,
            alternatives=[],
            litellm_yaml=_litellm_snippet(current_model, [], task_pattern),
            summary=(
                f"{current.provider}/{current.model} is already the cheapest "
                f"option meeting quality band {min_quality} for {task_pattern}. Nothing to do."
            ),
        )
    top = peers[:3]
    current_avg = _avg(current)
    alternatives: List[RoutingAlternative] = []
    for m in top:
        delta_pct = 100.0 * (current_avg - _avg(m)) / current_avg
        alternatives.append(
            RoutingAlternative(
                provider=m.provider,
                model=m.model,
                input_per_million_usd=m.input_per_million,
                output_per_million_usd=m.output_per_million,
                avg_cost_delta_pct=round(delta_pct, 1),
                quality_band=m.quality_band,
                quality_note=_quality_note(current.quality_band, m.quality_band),
                why=m.notes or f"Cheaper peer at quality band {m.quality_band}.",
            )
        )
    snippet = _litellm_snippet(current_model, top, task_pattern)
    primary = top[0]
    saving_pct = 100.0 * (current_avg - _avg(primary)) / current_avg
    summary = (
        f"Cheapest viable swap for {current.model} on {task_pattern}: "
        f"{primary.provider}/{primary.model} cuts ~{saving_pct:.0f}% of per-token cost, "
        f"{_quality_note(current.quality_band, primary.quality_band)}."
    )
    return RoutingPlan(
        current_model=current_model,
        current_model_known=True,
        task_pattern=task_pattern,
        min_quality_required=min_quality,
        alternatives=alternatives,
        litellm_yaml=snippet,
        summary=summary,
    )
